import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const viewer = readFileSync(new URL('./components/LoadoutViewer.vue', import.meta.url), 'utf8')
const archive = readFileSync(new URL('./components/LogsBattleArchive.vue', import.meta.url), 'utf8')
const atlas = readFileSync(new URL('./components/SigilAtlas.vue', import.meta.url), 'utf8')
const optimizer = readFileSync(new URL('./components/LoadoutOptimizer.vue', import.meta.url), 'utf8')
const optimizerWorker = readFileSync(new URL('./loadoutOptimizer.worker.js', import.meta.url), 'utf8')
const optimizerConfig = readFileSync(new URL('./loadoutScenarioConfig.js', import.meta.url), 'utf8')
const workshop = readFileSync(new URL('./components/LoadoutShareWorkshop.vue', import.meta.url), 'utf8')
const editor = readFileSync(new URL('./components/LoadoutEditor.vue', import.meta.url), 'utf8')
const iconCatalog = JSON.parse(readFileSync(new URL('./gameAssetIcons.json', import.meta.url), 'utf8'))

test('loadout workspace keeps only cross-loadout tools in the top navigation', () => {
  for (const id of ['view', 'atlas', 'battles']) {
    assert.match(viewer, new RegExp(`id: '${id}'`))
  }
  assert.doesNotMatch(viewer, /id: 'optimizer'|id: 'share'/)
  assert.match(viewer, /@wheel="scrollWorkspaceModes"/)
  assert.match(viewer, /\.loadout-subnav \{[\s\S]*?display:flex;[\s\S]*?flex-wrap:nowrap;[\s\S]*?overflow-x:auto;/)
  assert.match(viewer, /\.loadout-subnav button\.active \{[\s\S]*?background:transparent;[\s\S]*?box-shadow:none;/)
  assert.doesNotMatch(viewer, /<small>\{\{ item\.mark \}\}<\/small>/)
  assert.doesNotMatch(viewer, /<em>\{\{ item\.description \}\}<\/em>/)
})

test('character-specific share image stays in preview while smart loadout lives in the editor factor header', () => {
  assert.match(viewer, /class="loadout-detail-actions"/)
  assert.match(viewer, /编辑此配装/)
  assert.match(viewer, /生成分享图/)
  assert.match(viewer, /<LoadoutShareWorkshop embedded :group="shareGroup\(lo\)"/)
  assert.doesNotMatch(viewer, /class="factor-strategy-switch"/)
  assert.doesNotMatch(viewer, /<LoadoutOptimizer embedded/)
  assert.match(editor, /class="factor-workspace-tabs"/)
  assert.match(editor, /手动配装/)
  assert.match(editor, /按技能配装/)
  assert.match(editor, /<LoadoutOptimizer embedded[\s\S]*?:base-loadout="optimizerBaseLoadout"[\s\S]*?@apply="applyOptimizerPlan"/)
  assert.match(viewer, /@container loadout-viewer \(max-width:560px\)[\s\S]*?\.loadout-detail-actions \{ grid-template-columns:1fr; \}/)
})

test('save and character selectors state their downstream ownership and omit manual refresh', () => {
  assert.match(viewer, /第一步 · 选择来源存档/)
  assert.match(viewer, /后续角色、库存优化和写入目标都绑定这里选择的存档/)
  assert.match(viewer, /第二步 · 选择角色/)
  assert.match(viewer, /优化和分享都会使用当前角色数据/)
  assert.doesNotMatch(viewer, />刷新<\/button>/)
})

test('known unmapped weapons keep a themed first-column placeholder in loadout cards', () => {
  const knownUnmappedWeaponHashes = ['2C4CAADD', 'DFBB5727', '73D34F1B', 'DA807CA2']
  for (const hash of knownUnmappedWeaponHashes) {
    assert.equal(iconCatalog.weapons.byHash[hash] || '', '', `${hash} stays explicitly unmapped`)
  }
  assert.match(viewer, /<img v-if="loadoutWeaponIcon\(lo\)" class="loadout-weapon-icon"[\s\S]*?<span v-else class="loadout-weapon-icon loadout-weapon-icon-fallback"/)
  assert.match(viewer, /:aria-label="tx\('武器图标未收录', 'Weapon icon not cataloged'\)"/)
  assert.match(viewer, /\.loadout-weapon-icon \{[^}]*box-sizing:border-box;[^}]*width:62px;[^}]*height:44px;/)
  assert.match(viewer, /\.loadout-weapon-icon-fallback \{[^}]*display:grid;[^}]*border:1px dashed var\(--border-default\);[^}]*background:var\(--surface-sunken\);/)
})

test('large workspace tools stay outside the initial page bundle', () => {
  for (const component of ['LoadoutEditor', 'SigilAtlas', 'LoadoutShareWorkshop', 'LogsBattleArchive']) {
    assert.match(viewer, new RegExp(`const ${component} = defineAsyncComponent`))
  }
  assert.match(editor, /const LoadoutOptimizer = defineAsyncComponent/)
  assert.doesNotMatch(viewer, /import LoadoutEditor from '\.\/LoadoutEditor\.vue'/u)
  assert.doesNotMatch(editor, /import LoadoutOptimizer from '\.\/LoadoutOptimizer\.vue'/u)
})

test('catalog-heavy atlas stays mounted while contextual tools stay with their loadout', () => {
  assert.match(viewer, /<KeepAlive v-else-if="mode === 'atlas'">/)
  assert.match(viewer, /<SigilAtlas class="loadout-tool-subpage"/)
  assert.match(viewer, /cardToolOpen\(lo, 'share'\)/)
  assert.doesNotMatch(viewer, /cardToolOpen\(lo, 'optimizer'\)/)
})

test('optimizer apply enters the requested preset and stages a draft before save', () => {
  assert.match(optimizer, /emit\('apply'/)
  assert.match(optimizer, /回填完整方案到草稿/)
  assert.match(optimizer, /applyResult\(result\)/)
  assert.match(optimizer, /!result\?\.picked\?\.length && !result\?\.equipment\?\.length/)
  assert.match(viewer, /:preferred-unit-id="editorTargetUnitId"/)
  assert.match(editor, /function stageOptimizerEquipment\(result\)/)
  assert.match(editor, /function stageOptimizerPlan\(payload\)/)
  assert.match(editor, /function applyOptimizerPlan\(payload\)/)
  assert.match(editor, /weaponSlotId/)
  assert.match(editor, /optimizerWeaponEdit/)
  assert.match(editor, /weaponTranscendence/)
  assert.match(editor, /transcendence: targetTranscendence/)
  assert.match(editor, /writeGlobalSummons\.value = true/)
  assert.match(editor, /if \(!appliedCandidates && !equipmentChanges\) return false/)
  assert.match(editor, /factorWorkspaceMode\.value = 'manual'/)
  assert.match(editor, /请核对武器、祝福、召唤石、因子和最终技能等级后保存/)
})

test('smart loadout supports exact skill levels and owned-first gap construction', () => {
  assert.match(optimizer, /自动推荐/)
  assert.match(optimizer, /按技能目标配装/)
  assert.match(optimizer, /<CatalogSelect v-model="pendingTraitId"/)
  assert.match(optimizer, /class="skill-target-entry"/)
  assert.match(optimizer, /addPendingTrait/)
  assert.match(optimizer, /setTargetLevel/)
  assert.match(optimizer, /可添加任意数量/)
  assert.match(optimizer, /function moveTrait\(index, offset\)/)
  assert.match(optimizer, /completedPrefix/)
  assert.doesNotMatch(optimizer, /最多 4 项|up to 4|selected\.length >= 4|selected\.value\.length < 4/)
  assert.match(optimizer, /cap: item\.targetLevel/)
  assert.match(optimizer, /背包优先，缺少时制造/)
  assert.match(optimizer, /'owned-first': \[\.\.\.inventoryCandidates, \.\.\.catalogCandidates\]/)
  assert.match(optimizer, /constructedCount/)
  assert.match(optimizer, /\.optimizer-intent button\.active \{[\s\S]*?background:transparent;[\s\S]*?box-shadow:none;/)
  assert.match(editor, /next\.some\(entry => entry\?\.kind === 'construct'\)/)
  assert.match(editor, /为 \$\{constructed\} 个缺口准备独立新因子/)
})

test('optimizer handoff preserves exact catalog hashes and keeps remaining preset slots', () => {
  assert.match(editor, /exactSigilHash:\s*candidate\.exactSigilHash/)
  assert.match(editor, /exactPrimaryTraitHash:\s*candidate\.exactPrimaryTraitHash/)
  assert.match(editor, /exactSecondaryTraitHash:\s*candidate\.exactSecondaryTraitHash/)
  assert.match(editor, /for \(const entry of baseSlots\)/)
  assert.match(optimizer, /function resultPreviewSlots\(result\)/)
  assert.match(optimizer, /for \(const base of props\.baseLoadout\?\.sigils \|\| \[\]\)/)
  assert.match(optimizer, /while \(rows\.length < 12\)/)
  assert.match(editor, /const optimizerBaseLoadout = computed/)
  assert.match(editor, /sigils: factorSlotCards\.value\.filter\(card => !card\.empty\)/)
  assert.match(editor, /weaponSlotId: Number\(form\.value\.weaponSlotId/)
  assert.match(editor, /mastery: selectedMasteryHashes\.value\.slice\(\)/)
  assert.match(editor, /summonSlotIds: summonSlotIds\.value\.slice\(\)/)
})

test('optimizer embeds the editor visual language and exposes an understandable stable Top 10', () => {
  assert.match(optimizer, /<header v-if="!embedded" class="optimizer-heading">/)
  assert.match(optimizer, /const displayResults = computed\(\(\) => \{[\s\S]*?return plan\.slice\(0, 10\)[\s\S]*?\}\)/)
  assert.match(optimizer, /isResultExpanded\(result, index\)/)
  assert.match(optimizer, /function compareDisplayResults\(left, right\)/)
  assert.match(optimizer, /纯背包可达/)
  assert.match(optimizer, /需要制造/)
  assert.match(optimizer, /部分满足/)
  assert.match(optimizer, /class="result-group-heading"/)
  assert.match(optimizer, /class="[^"]*\bresult-sigil-grid\b[^"]*"/)
  assert.match(optimizer, /十二个因子槽预览/)
  assert.match(optimizer, /伤害上限核对/)
  assert.match(optimizer, /上限前伤害/)
  assert.match(optimizer, /当前动作上限/)
  assert.match(optimizer, /上限利用率/)
  assert.match(optimizer, /combatResultPriority/)
  assert.match(optimizer, /conditionalTraitIds: conditionalTraitIds\.value/)
  assert.match(optimizer, /buildCatalogCandidates\(atlas\.value, targets, ownerCode\.value\)/)
  assert.match(optimizer, /inventorySnapshot\.value[\s\S]*?inventoryCombatScenario\(\)/)
  assert.match(optimizer, /key === loadedInventoryKey\.value && inventorySnapshot\.value/)
  assert.match(optimizer, /const retainedCandidates = inventoryCandidates[\s\S]*?\.filter/)
  assert.match(optimizer, /const catalogSolveCandidates = includeRetained\(catalogCandidates\)/)
  assert.match(optimizer, /const tableSolveCandidates = includeRetained\(tableCandidates\)/)
  assert.match(optimizer, /baseSigils,/)
  assert.match(optimizer, /combatMode\.value \? \{\} : \{ 'owned-first'/)
  assert.match(optimizer, /\.chosen-trait img \{ width:32px; height:32px;/)
  assert.match(optimizer, /font-size:16px/)
  assert.match(optimizer, /font-size:14px/)
  assert.match(optimizer, /font-size:13px/)
  assert.match(optimizer, /font-size:12px/)
})

test('function artwork pipeline packages only the high-quality displayed images', () => {
  const generator = readFileSync(new URL('../scripts/generate_function_assets.mjs', import.meta.url), 'utf8')
  assert.doesNotMatch(generator, /thumb:\s*\{/)
  assert.match(generator, /display:\s*\{/)
  assert.doesNotMatch(generator, /variants\.full|copyFile\(sourcePath/)
})

test('missing page artwork never renders a broken mascot image', () => {
  assert.match(viewer, /defineAsyncComponent/)
  const shell = readFileSync(new URL('./components/PatchTool.vue', import.meta.url), 'utf8')
  assert.match(shell, /<img v-if="currentSticker" class="sidebar-mascot-img"/)
})

test('battle archive states its read-only contract and exposes explicit disconnect', () => {
  assert.match(archive, /本机只读/)
  assert.match(archive, /不会注入游戏，也不会修改数据库/)
  assert.match(archive, /CloseLogsBattleArchive/)
  assert.match(archive, /await CloseLogsBattleArchive\(\)/)
  assert.doesNotMatch(archive, /onBeforeUnmount\([^)]*CloseLogsBattleArchive/)
  assert.doesNotMatch(archive, /UPDATE\s+encounters|DELETE\s+FROM|INSERT\s+INTO/i)
  assert.match(archive, /非 v1 协议记录/)
  assert.match(archive, /cursorTime: nextCursorTime\.value, cursorId: nextCursorID\.value/)
})

test('battle archive owns a persistent current-session damage capture mode', () => {
  assert.match(archive, /RuntimeDamageCaptureStart/)
  assert.match(archive, /RuntimeDamageCaptureSnapshot\(1024\)/)
  assert.match(archive, /window\.setTimeout\(refreshLiveCapture, 500\)/)
  assert.match(archive, /await RuntimeDamageCaptureStop\(\)/)
  assert.match(archive, /停止并恢复 Hook/)
  assert.match(archive, /sourceMode = 'live'; scheduleLivePolling\(\)/)
  assert.match(archive, /sourceMode = 'logs'; stopLivePolling\(\)/)
  assert.match(archive, /liveSourceOrdinals/)
  assert.match(archive, /当前窗口观测伤害/)
  assert.match(archive, /当前不冒充个人 DPS/)
	assert.match(archive, /onBeforeUnmount\(deactivateLivePolling\)/)
  assert.doesNotMatch(archive, /onBeforeUnmount\([^)]*RuntimeDamageCaptureStop/)
  assert.match(archive, /@container battle \(max-width:520px\) \{ \.archive-heading \{ align-items:stretch; flex-direction:column; \}/)
})

test('Logs entry describes the bounded recent-record scan without claiming the whole database', () => {
  assert.match(viewer, /扫描最近的兼容记录/)
  assert.match(viewer, /Scan recent supported records/)
  assert.doesNotMatch(viewer, /Parse every character in the database/)
})

test('optimizer distinguishes formula-ranked directions from exact custom trait coverage', () => {
  assert.match(optimizer, /按目标生成方案/)
  assert.match(optimizer, /targetFulfilment/)
  assert.match(optimizer, /高级战斗条件/)
  assert.match(optimizer, /武器技能、武器祝福、召唤石与因子会一起凑目标/)
  assert.match(optimizer, /专精和永久成长保持不变/)
  assert.match(optimizer, /profile\.value !== 'custom'/)
})

test('optimizer presets use versioned locale-independent character profiles and honest inventory scope', () => {
  for (const id of ['SKILL_020_00', 'SKILL_001_00', 'SKILL_069_00']) assert.match(optimizerConfig, new RegExp(id))
  assert.match(optimizerConfig, /LOADOUT_CHARACTER_PROFILE_VERSION/)
  assert.match(optimizerConfig, /LOADOUT_CHARACTER_PROFILES/)
  assert.match(optimizer, /LoadoutOptimizerEvidence/)
  assert.match(optimizer, /LoadoutOptimizerInventorySnapshot/)
  assert.match(optimizer, /LoadoutSimulateBuild/)
  assert.match(optimizer, /可识别实例中组合/)
  assert.match(optimizer, /可能也被其他预设引用/)
})

test('optimizer runs exact search off the UI thread and cancels stale jobs', () => {
  assert.match(optimizer, /new Worker\(new URL\('\.\.\/loadoutOptimizer\.worker\.js'/u)
  assert.match(optimizer, /solveWorker\?\.terminate\(\)/u)
  assert.match(optimizer, /generation !== solveGeneration/u)
  assert.match(optimizerWorker, /solveLoadoutSuggestions/u)
  assert.match(optimizerWorker, /solveEquipmentAwareSuggestions/u)
  assert.match(optimizerWorker, /solveMixedOptimizerDomains/u)
})

test('sigil atlas localizes every catalog category instead of exposing internal enum names', () => {
  for (const category of ['character_sigil', 'support_sigil', 'special_sigil', 'opus_sigil']) {
    assert.match(atlas, new RegExp(`${category}: \\[`))
  }
  assert.match(atlas, /categoryLabel\(entry\.category\)/)
})

test('sigil atlas prefills the existing loadout constructor without writing a save', () => {
  assert.match(atlas, /emit\('construct'/)
  assert.match(atlas, /送入配装构造器/)
  assert.match(viewer, /@construct="constructFromAtlas"/)
  assert.match(viewer, /:pending-atlas-construct="pendingAtlasConstruct"/)
  assert.match(editor, /consumePendingAtlasConstruct/)
  assert.match(editor, /已从因子图鉴预填构造器，请确认槽位与等级后保存/)
  assert.doesNotMatch(atlas, /LoadoutApplyWithResources|WriteSave|SaveChanges/)
})

test('sigil atlas hands a legal trait direction only to the embedded optimizer', () => {
  assert.match(atlas, /emit\('optimize'/)
  assert.match(atlas, /送入优化目标/)
  assert.match(viewer, /@optimize="openAtlasOptimizer"/)
  assert.match(optimizer, /pendingTarget/)
  assert.doesNotMatch(atlas, /share-note|加入分享图说明|Add to Share Description/)
  assert.match(atlas, /class="ui-btn[^"]*\batlas-constructor-action\b[^"]*"/)
  assert.doesNotMatch(atlas, /class="ui-btn is-primary"[^>]*sendToConstructor/)
  assert.doesNotMatch(viewer, /pendingShareDescription|suggested-description|@share-note/)
  assert.doesNotMatch(workshop, /suggestedDescription/)
})

test('share image export waits for image decoding before capture', () => {
  assert.match(workshop, /waitForImages/)
  assert.match(workshop, /\.decode\?\.\(\)/)
  assert.match(workshop, /html-to-image/)
  assert.match(workshop, /if \(image\.complete\)[\s\S]*?if \(!image\.naturalWidth\) throw new Error/)
  assert.match(workshop, /window\.setTimeout\([\s\S]*?素材加载超时/)
})

test('share image reuses capped combined skills from the application preview', () => {
  assert.match(workshop, /preview\.value\?\.combinedSkills/)
  assert.match(workshop, /trait\.rawLevel > trait\.level/)
  assert.match(workshop, /原始等级 · 未含召唤石/)
})

test('share image uses the blue card artwork, light actions, and bounded responsive preview', () => {
  assert.match(workshop, /share-card-sky-frame-v2\.webp/)
  assert.match(workshop, /backdropUrl/)
  assert.match(workshop, /class="share-card-backdrop"/)
  assert.doesNotMatch(workshop, /parchment-ui/)
  assert.match(workshop, /const portraitOpacity = ref\(88\)/)
  assert.match(workshop, /type="range" min="64" max="100"/)
  assert.match(workshop, /profile\?\.weaponSafeFrame/)
  assert.match(workshop, /--portrait-safe-scale/)
  assert.match(workshop, /object-fit:var\(--portrait-fit,cover\)/)
  assert.match(workshop, /object-position:var\(--portrait-focus,50% 28%\)/)
  assert.match(workshop, /\.share-portrait \{[^}]*z-index:1;[^}]*width:88%;[^}]*height:138%;/)
  assert.match(workshop, /\.share-wash \{ position:absolute; z-index:2;/)
  assert.match(workshop, /\.canvas-title \{ position:relative; z-index:3;/)
  assert.match(workshop, /\.canvas-weapon > img,[^}]*width:132px;[^}]*height:62px;/)
  assert.match(workshop, /class="ui-btn share-action share-action-primary"/)
  assert.doesNotMatch(workshop, /class="ui-btn is-primary"[^>]*@click="download"/)
  assert.match(workshop, /new ResizeObserver\(updatePreviewScale\)/)
  assert.match(workshop, /previewStageStyle/)
  assert.match(workshop, /transform:scale\(var\(--preview-scale,1\)\)/)
  assert.match(workshop, /\.share-preview-shell \{[^}]*overflow:hidden;/)
})

test('expanded atlas metadata stays flat and visually aligned with the factor icon', () => {
  assert.match(atlas, /\.atlas-entry-detail dl div \{[^}]*min-height:42px;[^}]*border:1px solid var\(--border-soft\);[^}]*border-radius:var\(--radius-sm\);[^}]*background:var\(--surface-card-pop\);[^}]*box-shadow:none;/)
  assert.doesNotMatch(atlas, /\.atlas-entry-detail dl div \{[^}]*background:var\(--surface-sunken\)/)
})

test('all three share formats keep fixed export pixels and an internal height budget', () => {
  for (const output of ['1920x1080', '1440x1920', '1600x1600']) assert.match(workshop, new RegExp(output))
  assert.match(workshop, /width: exportConfig\.value\.width,[\s\S]*?height: exportConfig\.value\.height/)
  assert.match(workshop, /style: \{ transform: 'none'/)
  assert.match(workshop, /\.canvas-content \{ position:absolute;[^}]*top:126px; right:42px; bottom:88px; left:42px;[^}]*grid-template-rows:82px minmax\(0,1fr\);[^}]*overflow:hidden;/)
  assert.match(workshop, /\.share-canvas\.is-portrait \.canvas-title \{ height:144px; padding:24px 32px 10px;/)
  assert.match(workshop, /\.share-canvas\.is-portrait \.canvas-content \{ top:144px; right:32px; bottom:90px;/)
  assert.match(workshop, /\.share-canvas\.is-portrait \.share-wash \{[^}]*linear-gradient\(180deg,/)
  assert.match(workshop, /\.share-canvas\.is-portrait \.canvas-content \{[^}]*grid-template-rows:auto minmax\(0,1fr\) auto;[^}]*align-content:stretch;/)
  assert.match(workshop, /\.share-canvas\.is-portrait \.canvas-sigils \{[^}]*grid-template-rows:auto minmax\(0,1fr\);/)
  assert.match(workshop, /\.share-canvas\.is-portrait \.canvas-sigils > div \{[^}]*grid-template-rows:repeat\(6,minmax\(0,1fr\)\);/)
  assert.match(workshop, /\.share-canvas\.is-square \.canvas-title \{ height:110px; padding:14px 32px 6px;/)
  assert.match(workshop, /\.share-canvas\.is-square \.canvas-content \{ top:110px; right:32px; bottom:56px;/)
  assert.match(workshop, /\.share-canvas\.is-square \.canvas-content \{[^}]*grid-template-rows:auto auto auto;[^}]*align-content:start;/)
  assert.match(workshop, /\.share-canvas\.is-square \.share-portrait \{ top:-24%;[^}]*height:132%;/)
  assert.match(workshop, /\.share-canvas\.is-square \.canvas-levels \{ grid-template-columns:repeat\(3,minmax\(0,1fr\)\);/)
  assert.match(workshop, /\.canvas-levels \{[^}]*grid-template-columns:repeat\(3,minmax\(0,1fr\)\);/)
  assert.match(workshop, /\.share-canvas\.is-portrait \.canvas-summary \{[^}]*grid-template-rows:auto;[^}]*align-content:start;/)
  assert.match(workshop, /\.canvas-summary > div \{[^}]*align-content:start;/)
  assert.match(workshop, /\(selected\?\.sigils \|\| \[\]\)\.slice\(0, 12\)/)
  assert.match(workshop, /canvas-icon-fallback/)
  assert.match(workshop, /watch\(shareUrl, scheduleQR, \{ immediate: true \}\)/)
  assert.match(workshop, /await waitForCurrentQR\(\)[\s\S]*?await nextTick\(\)/)
  assert.match(workshop, /assertCanvasFits\(canvasRef\.value\)/)
  assert.match(workshop, /element\.scrollHeight > element\.clientHeight \+ 2/)
  assert.match(workshop, /二维码生成失败，PNG 未导出/)
})
