import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = name => readFile(new URL(`./components/${name}`, import.meta.url), 'utf8')

test('natural-drop lab keeps deployment scoped and responsive', async () => {
  const source = await read('NaturalDropLab.vue')
  assert.match(source, /GetNaturalDropWorkspace/)
  assert.match(source, /DeployNaturalDropMod/)
  assert.match(source, /RestoreNaturalDropDefaults/)
  assert.match(source, /SelectNaturalDropGameExecutable/)
  assert.match(source, /indexSummary/)
  assert.match(source, /data\.i.*back/i)
  assert.match(source, /hasConflicts/)
  assert.match(source, /selectedWrightstones/)
  assert.match(source, /wrightstoneOnly/)
  assert.match(source, /天然祝福石/)
  assert.match(source, /主 Lv20、副 Lv15、副 Lv10/)
  assert.doesNotMatch(source, /ModsDirectory|modsDir/)
  assert.match(source, /@container natural-drop \(max-width:620px\)/)
  assert.doesNotMatch(source, /style="[^"]*(?:background|color)/)
})

test('audio mixer exposes the built-in runtime and themed controls', async () => {
  const source = await read('AudioMixerLab.vue')
  assert.match(source, /DeployAudioMixerMod/)
  assert.match(source, /RemoveAudioMixerMod/)
  assert.match(source, /workspace\?\.owned/)
  assert.match(source, /audio-range::-webkit-slider-thumb/)
  assert.match(source, /unknown and shared events stay untouched/i)
  assert.match(source, /gbfr-codex-audio-presets-v1/)
  assert.match(source, /const uiVolume = ref\(100\)/)
  assert.match(source, /uiVolume: uiVolume\.value/)
  assert.match(source, /ui\*\.bnk · Volume_SE/)
  assert.match(source, /界面音效/)
  assert.match(source, /function savePreset\(\)/)
  assert.match(source, /载入后仍需在底部确认保存/)
  assert.match(source, /第一步 · 连接当前游戏/)
  assert.match(source, /第三步 · 应用到当前游戏/)
  assert.match(source, /BUILT-IN RUNTIME/)
  assert.doesNotMatch(source, /SelectAudioMixerModsDirectory|modsDir/)
  assert.match(source, /@container audio-lab \(max-width:520px\)/)
  assert.match(source, /\.ui-track/)
  assert.doesNotMatch(source, /#[0-9a-f]{3,8}/i)
})

test('camera lab owns injection and themed controls without an external loader', async () => {
  const source = await read('CameraLab.vue')
  assert.match(source, /DeployCameraMod/)
  assert.match(source, /RemoveCameraMod/)
  assert.match(source, /workspace\?\.owned/)
  assert.match(source, /camera-range::-webkit-slider-thumb/)
  assert.match(source, /第一步 · 启动并连接游戏/)
  assert.match(source, /第三步 · 应用到当前游戏/)
  assert.match(source, /let refreshRequest = 0/)
  assert.match(source, /request !== refreshRequest/)
  assert.match(source, /Boolean\(workspace\.value\?\.gameRunning\)/)
  assert.doesNotMatch(source, /SelectCameraModsDirectory|modsDir/)
  assert.match(source, /type="range" min="0\.001" max="1"/)
  assert.match(source, /@container camera-lab \(max-width:480px\)/)
  assert.doesNotMatch(source, /#[0-9a-f]{3,8}/i)
})

test('virtual sigil lab exposes real-instance slots, presets, and overflow without save writes', async () => {
  const source = await read('VirtualSigilLab.vue')
  assert.match(source, /DeployVirtualSigilMod/)
  assert.match(source, /RemoveVirtualSigilMod/)
  assert.match(source, /primaryTraitMaxLevel/)
  assert.match(source, /trait\.overflow/)
  assert.match(source, /savePreset/)
  assert.match(source, /characterAssetIcon/)
  assert.match(source, /import \{[^}]*FindSaveFiles[^}]*GetLastSavePath[^}]*\} from '\.\.\/\.\.\/wailsjs\/go\/backend\/App'/)
  assert.match(source, /import \{ SelectSigilInputSave \} from '\.\.\/\.\.\/wailsjs\/go\/backend\/SigilGen'/)
  assert.match(source, /watch\(pageCount, count => \{ page\.value = Math\.min\(page\.value, count - 1\) \}\)/)
  assert.match(source, /第一步 · 选择来源存档/)
  assert.match(source, /第三步 · 应用到当前游戏/)
  assert.match(source, /BUILT-IN/)
  assert.doesNotMatch(source, /SelectVirtualSigilModsDirectory|modsDir/)
  assert.match(source, /invalidSelections/)
  assert.match(source, /来源实例失效/)
  assert.match(source, /invalidSelections\.value\.length === 0/)
  assert.match(source, /@container virtual-lab \(max-width:500px\)/)
  assert.doesNotMatch(source, /#[0-9a-f]{3,8}/i)
})

test('patch tool lazy-loads the mod labs', async () => {
  const source = await read('PatchTool.vue')
  assert.match(source, /audioMixer: \(\) => import\('\.\/AudioMixerLab\.vue'\)/)
  assert.match(source, /naturalDrop: \(\) => import\('\.\/NaturalDropLab\.vue'\)/)
  assert.match(source, /camera: \(\) => import\('\.\/CameraLab\.vue'\)/)
  assert.match(source, /virtualSigils: \(\) => import\('\.\/VirtualSigilLab\.vue'\)/)
  assert.match(source, /items: \['saveDiff', 'naturalDrop', 'audioMixer', 'camera', 'virtualSigils'/)
})
