import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = name => readFile(new URL(`./components/${name}`, import.meta.url), 'utf8')

test('natural-drop lab keeps deployment scoped and responsive', async () => {
  const source = await read('NaturalDropLab.vue')
  assert.match(source, /GetNaturalDropWorkspace/)
  assert.match(source, /DeployNaturalDropMod/)
  assert.match(source, /RestoreNaturalDropDefaults/)
  assert.match(source, /SelectNaturalDropGameExecutable/)
  assert.match(source, /indexSummary/)
  assert.match(source, /data\.i.*back/i)
  assert.match(source, /hasConflicts/)
  assert.match(source, /selectedWrightstones/)
  assert.match(source, /class="advanced-drop-panel"/)
  assert.doesNotMatch(source, /transmarvelResultMode/)
  assert.match(source, /selectedSigils/)
  assert.match(source, /Transmarvel 因子/)
  assert.match(source, /Transmarvel 祝福石/)
  assert.match(source, /主词条 Lv20/)
  assert.match(source, /副词条 Lv15/)
  assert.match(source, /副词条 Lv10/)
  assert.match(source, /程序内置 · 11\/11 逐张 SHA-256 校验/)
  assert.match(source, /维护者对照/)
  assert.match(source, /builtin:\/\/dlc-2\.0\.2/)
  assert.match(source, /onActivated\(\(\) => \{[\s\S]*?refreshWorkspace/)
  assert.doesNotMatch(source, /尚未选择 system\/table/)
  assert.doesNotMatch(source, /ModsDirectory|modsDir/)
  assert.match(source, /@container natural-drop \(max-width:620px\)/)
  assert.doesNotMatch(source, /style="[^"]*(?:background|color)/)
})

test('audio mixer exposes the built-in runtime and themed controls', async () => {
  const source = await read('AudioMixerLab.vue')
  assert.match(source, /DeployAudioMixerMod/)
  assert.match(source, /RemoveAudioMixerMod/)
  assert.match(source, /workspace\?\.owned/)
  assert.match(source, /audio-range::-webkit-slider-thumb/)
  assert.match(source, /unknown and shared events stay untouched/i)
  assert.match(source, /gbfr-codex-audio-presets-v1/)
  assert.match(source, /const uiVolume = ref\(100\)/)
  assert.match(source, /uiVolume: uiVolume\.value/)
  assert.match(source, /ui\*\.bnk · Volume_SE/)
  assert.match(source, /界面音效/)
  assert.match(source, /function savePreset\(\)/)
  assert.match(source, /载入后还要在页面底部确认应用/)
  assert.match(source, /第一步 · 启动游戏并确认连接/)
  assert.match(source, /诊断日志/)
  assert.match(source, /默认关闭；只有排查声音识别问题时才需要开启/)
  assert.match(source, /BUILT-IN RUNTIME/)
  assert.doesNotMatch(source, /SelectAudioMixerModsDirectory|modsDir/)
  assert.match(source, /@container audio-lab \(max-width:520px\)/)
  assert.match(source, /\.ui-track/)
  assert.doesNotMatch(source, /#[0-9a-f]{3,8}/i)
})

test('camera lab owns injection and themed controls without an external loader', async () => {
  const source = await read('CameraLab.vue')
  assert.match(source, /DeployCameraMod/)
  assert.match(source, /RemoveCameraMod/)
  assert.match(source, /workspace\?\.owned/)
  assert.match(source, /camera-range::-webkit-slider-thumb/)
  assert.match(source, /第一步 · 启动游戏并确认连接/)
  assert.match(source, /第三步 · 应用到当前游戏/)
  assert.match(source, /let refreshRequest = 0/)
  assert.match(source, /request !== refreshRequest/)
  assert.match(source, /Boolean\(workspace\.value\?\.gameRunning\)/)
  assert.doesNotMatch(source, /SelectCameraModsDirectory|modsDir/)
  assert.match(source, /type="range" min="0\.001" max="1"/)
  assert.match(source, /@container camera-lab \(max-width:480px\)/)
  assert.doesNotMatch(source, /#[0-9a-f]{3,8}/i)
})

test('virtual sigil lab exposes real-instance slots, direct safe construction, presets, and overflow', async () => {
  const source = await read('VirtualSigilLab.vue')
  assert.match(source, /DeployVirtualSigilMod/)
  assert.match(source, /RemoveVirtualSigilMod/)
  assert.match(source, /primaryTraitMaxLevel/)
  assert.match(source, /trait\.overflow/)
  assert.match(source, /savePreset/)
  assert.match(source, /characterAssetIcon/)
  assert.match(source, /import \{[^}]*FindSaveFiles[^}]*GetLastSavePath[^}]*\} from '\.\.\/\.\.\/wailsjs\/go\/backend\/App'/)
  assert.match(source, /import \{ SelectSigilInputSave \} from '\.\.\/\.\.\/wailsjs\/go\/backend\/SigilGen'/)
  assert.match(source, /watch\(pageCount, count => \{ page\.value = Math\.min\(page\.value, count - 1\) \}\)/)
  assert.match(source, /第一步 · 选择因子来源/)
  assert.match(source, /第三步 · 应用到当前游戏/)
  assert.match(source, /@container virtual-lab \(max-width:1600px\)/)
  assert.match(source, /\.dock-actions \{[^}]*flex-wrap:wrap/)
  assert.match(source, /BUILT-IN/)
  assert.doesNotMatch(source, /SelectVirtualSigilModsDirectory|modsDir/)
  assert.match(source, /invalidSelections/)
  assert.match(source, /来源实例失效/)
  assert.match(source, /invalidSelections\.value\.length === 0/)
  assert.match(source, /CreateVirtualSigilSource/)
  assert.match(source, /制造后自动放入当前虚拟槽/)
  assert.match(source, /游戏运行时不能改写默认存档/)
  assert.match(source, /\.trait-grid article:only-child \{ grid-column:1\/-1; \}/)
  assert.match(source, /\.trait-grid dl \{ display:grid; grid-template-columns:repeat\(3,minmax\(58px,1fr\)\)/)
  assert.match(source, /\.preset-panel > header > div:last-child \{ display:grid; grid-template-columns:minmax\(180px,1fr\) auto;/)
  assert.match(source, /\.empty-state \{[^}]*text-align:left;/)
  assert.match(source, /@container virtual-lab \(max-width:500px\)/)
  assert.doesNotMatch(source, /#[0-9a-f]{3,8}/i)
})

test('patch tool lazy-loads the mod labs', async () => {
  const source = await read('PatchTool.vue')
  assert.match(source, /audioMixer: \(\) => import\('\.\/AudioMixerLab\.vue'\)/)
  assert.match(source, /naturalDrop: \(\) => import\('\.\/NaturalDropLab\.vue'\)/)
  assert.match(source, /camera: \(\) => import\('\.\/CameraLab\.vue'\)/)
  assert.match(source, /virtualSigils: \(\) => import\('\.\/VirtualSigilLab\.vue'\)/)
  assert.match(source, /items: \['runtimeMonitor', 'loadout'\]/)
  assert.match(source, /items: \['runtimeQOL', 'virtualSigils', 'audioMixer', 'camera', 'spatialTools', 'patchCombat', 'patchCharacters', 'patchQuest', 'monster'\]/)
  assert.match(source, /items: \['naturalDrop', 'selectedItemMonitor', 'formulaSampler', 'compatibility', 'patch', 'language'\]/)
})
